interface Args {
  agnostic_nms: boolean;
  amp: boolean;
  angle: number;
  augment: boolean;
  auto_augment: string;
  batch: number;
  bgr: number;
  box: number;
  cache: boolean;
  cfg: null | string;
  classes: null | string;
  close_mosaic: number;
  cls: number;
  compile: boolean;
  conf: null | string;
  copy_paste: number;
  copy_paste_mode: string;
  cos_lr: boolean;
  cutmix: number;
  data: string;
  degrees: number;
  deterministic: boolean;
  device: null | string;
  dfl: number;
  dnn: boolean;
  dropout: number;
  dynamic: boolean;
  embed: null | string;
  end2end: null | string;
  epochs: number;
  erasing: number;
  exist_ok: boolean;
  fliplr: number;
  flipud: number;
  format: string;
  fraction: number;
  freeze: null | string;
  half: boolean;
  hsv_h: number;
  hsv_s: number;
  hsv_v: number;
  imgsz: number;
  int8: boolean;
  iou: number;
  keras: boolean;
  kobj: number;
  line_width: null | string;
  lr0: number;
  lrf: number;
  mask_ratio: number;
  max_det: number;
  mixup: number;
  mode: string;
  model: string;
  momentum: number;
  mosaic: number;
  multi_scale: number;
  name: string;
  nbs: number;
  nms: boolean;
  opset: null | string;
  optimize: boolean;
  optimizer: string;
  overlap_mask: boolean;
  patience: number;
  perspective: number;
  plots: boolean;
  pose: number;
  pretrained: boolean;
  profile: boolean;
  project: null | string;
  rect: boolean;
  resume: boolean;
  retina_masks: boolean;
  rle: number;
  save: boolean;
  save_conf: boolean;
  save_crop: boolean;
  save_frames: boolean;
  save_json: boolean;
  save_period: number;
  save_txt: boolean;
  scale: number;
  seed: number;
  shear: number;
  show: boolean;
  show_boxes: boolean;
  show_conf: boolean;
  show_labels: boolean;
  simplify: boolean;
  single_cls: boolean;
  source: null | string;
  split: string;
  stream_buffer: boolean;
  task: string;
  time: null | string;
  tracker: string;
  translate: number;
  val: boolean;
  verbose: boolean;
  vid_stride: number;
  visualize: boolean;
  warmup_bias_lr: number;
  warmup_epochs: number;
  warmup_momentum: number;
  weight_decay: number;
  workers: number;
  workspace: null | string;
}

export interface Yolo {
  id: string;
  name: string;
  path: string;
  csv_path: string;
  total_test_images: number;
  total_train_images: number;
  total_val_images: number;
  args: Args;
  images: { name: string; url: string }[];
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date;
}

export interface FindYoloQuery {
  content: Yolo[];
}
